import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String tmp() {
        Scanner in = new Scanner(System.in);
        return in.nextLine();
    }


    public String getGreeting() {
        String theName = askUserForName("Please tyoe your name!");
        return "Hello " + theName;
    }
    public String askUserForName(String s) {
        String TheString;
        Scanner sc = new Scanner(System.in);
        do {
            System.out.println(s);
            TheString = sc.nextLine();
        } while (TheString.length()<1);
        return TheString;
    }

    public static void main(String args) {
        System.out.println(new App().getGreeting());
    }
}
