/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;

import java.io.ByteArrayInputStream;

import static org.testng.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        System.setIn(new ByteArrayInputStream("asdf".getBytes()));
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    //---------------------------------------------------
    @Test public void Test_askUserForName(){
        //given
        App classUnderTest = new App();
        System.setIn(new ByteArrayInputStream("asdf".getBytes()));
        //when
        String testString = classUnderTest.askUserForName("asdf");
        //then
        assertEquals(testString,"asdf");
    }
}
